##################
# ImageTransformer
##################
tag: Null
random_seed: 0

##############
# Dataloader #
##############
# mnist, fmnist, cifar10, imagewoof
dataloader:
  dataset: "cifar10"
  num_workers: 2

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

#########
# Model #
#########
transformer:
  n_blocks: 4
  image_to_sequence:
    patch_size: 1
  transformer_block:
    hidden_expansion: 4
    dropout_prob: 0.2
  self_attention:
    sequence_length: 64
    n_heads: 32
    head_dim: 4
    dropout_prob: 0.2
    use_bias: False
    use_mask: True
  classifier:
    bla: None

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  n_epochs: 500
  learning_rate: 4.0e-4
  weight_decay: 0
  lr_step_size: 200
  lr_gamma: 0.5
  batch_size: 64
  grad_norm_clip: 1.0

###########
# Summary #
###########
summary:
  add_graph: false
  add_sample_batch: true
  add_hparams: false
  add_patch_embedding_weights:
    every_n_epochs: 10
  add_position_embedding_weights:
    every_n_epochs: 10
  add_mask_weights:
    every_n_epochs: 10
  add_params_hist:
    every_n_epochs: -1
  save_train_stats:
    every_n_epochs: 1
  save_test_stats:
    every_n_epochs: 10
  save_model:
    every_n_epochs: -1

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
