##################
# ImageTransformer
##################
tag: Null
random_seed: 0

##############
# Dataloader #
##############
# mnist, fmnist, cifar10, imagewoof
dataloader:
  dataset: "cifar10"
  num_workers: 0

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

#########
# Model #
#########
transformer:
  n_blocks: 4
  image_to_sequence:
    patch_size: 1
  transformer_block:
    hidden_expansion: 4
    dropout_prob: 0
  self_attention:
    sequence_length: 4
    n_heads: 2
    head_dim: 4  # embedding dimension is n_heads * head_dim
    dropout_prob: 0
    use_bias: False
    use_mask: True
  # mask:
  #   use_mask: True
  #   type: causal, trainable_additive, trainable_multiplicative
  #   is_trainable: True
  classifier:
    param1: None

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  n_epochs: 500
  batch_size: 2
  weight_decay: 0
  learning_rate: 2.0e-4
  # learning_rate_step_every: 200
  # learning_rate_gamma: 0.5
  lr_step_size: 200
  lr_gamma: 0.5

###########
# Summary #
###########
summary:
  add_graph: false
  add_sample_batch: false
  add_hparams: false
  add_patch_embedding_weights:
    every_n_epochs: 10
  add_position_embedding_weights:
    every_n_epochs: 10
  add_mask_weights:
    every_n_epochs: 10
  add_params_hist:
    every_n_epochs: -1
  save_train_stats:
    every_n_epochs: 1
  save_test_stats:
    every_n_epochs: 10
  save_model:
    every_n_epochs: -1

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
