##################
# ImageTransformer
##################

# ---- Experiment specific parameters
experiment:
  tag: ""
  random_seed: 0
  device: "gpu"

########
# Data #
########
# cifar10, imagewoof
data:
  dataset: "cifar10"
  num_workers: 2

#########
# Model #
#########

image_transformer:
  n_blocks: 4
  image_to_sequence:
    patch_size: 2
    out_channels: 3
  transformer_block:
    multi_head_self_attention:
      n_heads: 8
      sequence_size: 16
    hidden_expansion: 4
  classifier:
    bla: None

###########
# Trainer #
###########

trainer:
  device: "gpu"
  random_seed: 0
  n_epochs: 400
  learning_rate: 1.0e-4
  weight_decay: 0.0
  lr_step_size: 200
  lr_gamma: 0.5
  batch_size: 64

###########
# Summary #
###########
summary:
  add_graph: true
  add_sample_batch: true
  save_train_stats_every_n_epochs: 1
  save_test_stats_every_n_epochs: 10
  add_params_hist_every_n_epochs: 50
  save_model_every_n_epochs: 50

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############
dirs:
  weights: "weights"
  runs: "runs"
  data: "data"

