##################
# ImageTransformer
##################
tag: Null
random_seed: 0

##############
# Dataloader #
##############
# mnist, cifar10, imagewoof
dataloader:
  dataset: "fmnist"
  num_workers: 2

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

#########
# Model #
#########
transformer:
  n_blocks: 8
  image_to_sequence:
    patch_size: 1
  transformer_block:
    hidden_expansion: 4
    dropout_prob: 0.1
  self_attention:
    sequence_length: 32
    n_heads: 4
    head_dim: 32
    dropout_prob: 0.1
    use_bias: False
    use_mask: True
  classifier:
    bla: None

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  n_epochs: 500
  learning_rate: 1.0e-4
  weight_decay: 0
  lr_step_size: 200
  lr_gamma: 0.5
  batch_size: 512
  grad_norm_clip: 1.0

###########
# Summary #
###########
summary:
  add_graph: false
  add_sample_batch: false
  add_hparams: false
  save_train_stats_every_n_epochs: 1
  save_test_stats_every_n_epochs: 10
  add_params_hist_every_n_epochs: 9999
  save_model_every_n_epochs: -1

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
