##################
# ImageTransformer
##################
tag: "h64d4"
random_seed: 42

##############
# Dataloader #
##############
# mnist, fmnist, cifar10, imagewoof, shakespeare, lexicap
dataloader:
  dataset: "lexicap"
  num_workers: 2

#########
# Model #
#########
transformer:
  n_blocks: 8
  max_sequence_length: 128
  image_to_sequence:
    patch_size: 1
    # sequence_length: 64  # TODO: Move sequence_length here for image transformer.
  token_embedding:
    is_trainable: true
    # Available encoding schemes: random_normal, sinusoidal
    encoding: "random_normal" 
  position_embedding:
    is_activated: true
    is_trainable: true
    # Available encoding schemes: ones, zeros, random_normal, sinusoidal
    encoding: "random_normal" 
  transformer_block:
    hidden_expansion: 4
    dropout_prob: 0.05
  self_attention:
    n_heads: 64
    head_dim: 4  # embedding dimension is n_heads * head_dim
    dropout_prob: 0.05
    use_bias: True 
  mask:
    is_activated: true
    is_trainable: true
    # Available masks: causal, trainable_additive, trainable_multiplicative 
    type: "causal" 
  classifier:
    param1: None

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  # n_epochs: 500
  num_update_steps: 10000
  batch_size: 64
  weight_decay: 0
  learning_rate: 1.0e-6
  # learning_rate_step_every: 200
  # learning_rate_gamma: 0.5
  lr_step_size: 200
  lr_gamma: 0.5
  grad_norm_clip: 1.0  # TODO: Use version below.
  gradient_clipping:
    is_activated: true
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "lexicap3"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 2000
  add_patch_embeddings:
    every_n_updates: -1 
  add_position_embeddings:
    every_n_updates: 2000
  add_token_embeddings:
    every_n_updates: 2000
  add_mask_weights:
    every_n_updates: 2000
  add_params_hist:
    every_n_updates: -1
  add_graph: false
  add_sample_batch: false
  add_hparams: false

###############
# Directories #
###############
dirs:  # TODO: dirs -> dir
  data: "data"
  runs: "runs"
  weights: "weights"
