###############
# Transformer #
###############
tag: ""
random_seed: 42

##############
# Dataloader #
##############
# mnist, fmnist, cifar10, imagewoof, shakespeare, lexicap, books
dataloader:
  dataset: "books"
  num_workers: 0

#########
# Model #
#########
transformer:
  n_blocks: 4
  max_sequence_length: 128
  image_to_sequence:
    patch_size: 1
    # sequence_length: 64  # TODO: Move sequence_length here for image transformer.
  token_embedding:
    is_trainable: true
    # Available encoding schemes: random_normal, sinusoidal
    encoding: "random_normal" 
  position_embedding:
    is_activated: true
    is_trainable: true
    # Available encoding schemes: ones, zeros, random_normal, sinusoidal
    encoding: "zeros" 
  transformer_block:
    hidden_expansion: 2
    dropout_prob: 0
  self_attention:
    n_heads: 2
    head_dim: 256  # embedding dimension is n_heads * head_dim
    dropout_prob: 0
    use_bias: true
  mask:
    is_activated: true
    is_trainable: true
    # Available masks: causal, trainable_additive, trainable_multiplicative 
    type: "trainable_additive" 

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  num_update_steps: 100000
  batch_size: 64
  weight_decay: 1.0e-6
  learning_rate:
    value: 3.0e-4
    step_size: 100000
    gamma: 0.5
  gradient_clipping:
    is_activated: true
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "books_3"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 5000
  add_patch_embeddings:
    every_n_updates: -1 
  add_position_embeddings:
    every_n_updates: 5000
  add_token_embeddings:
    every_n_updates: 5000
  add_mask_weights:
    every_n_updates: 5000
  add_params_hist:
    every_n_updates: -1
  add_graph: false
  add_sample_batch: false
  add_hparams: false

###############
# Directories #
###############
dirs:  # TODO: dirs -> dir
  data: "data"
  runs: "runs"
  weights: "weights"
